{
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "id": "b-8qomURBesI",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 1000,
          "referenced_widgets": [
            "589d11050c6d44bdb61bbb100db32051",
            "ed4c884dd423419aa35ce0402fc503ef",
            "31b1a5f9011b4fbfb22a29480a450873",
            "4aaa9a4fb3534575984e8e5c0689e752",
            "f953f66f4fad411cb0b4c63c59699dfd",
            "7bef11aa7ed74b2295b900735c6c5e7f",
            "695cd5959b99474fb8863b9edc8ae647",
            "69cd166494b3487a94906728cbb01313",
            "357c012a3cec4abb89541737910dbd52",
            "cd89bb062d0d4df99cfc693b4fc65caa",
            "1d1e04a0918b42fd86455f5f91ad1453"
          ]
        },
        "outputId": "36e4d764-97b2-4fdb-8fa7-91bdf2bc940e"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Original shape: (8000, 5)\n",
            "condition\n",
            "Migraine             564\n",
            "Asthma               559\n",
            "COVID-19             556\n",
            "Common Cold          547\n",
            "Bronchitis           541\n",
            "Diabetes             521\n",
            "Influenza            483\n",
            "Pneumonia            473\n",
            "Depression           398\n",
            "Gastroenteritis      395\n",
            "Sinusitis            394\n",
            "Tuberculosis         387\n",
            "Anemia               385\n",
            "Dengue               368\n",
            "Malaria              366\n",
            "Arthritis            356\n",
            "Hypertension         354\n",
            "Allergic Rhinitis    353\n",
            "Name: count, dtype: int64\n",
            "\n",
            "After balancing: (10152, 5)\n",
            "condition\n",
            "Malaria              564\n",
            "Bronchitis           564\n",
            "Pneumonia            564\n",
            "Dengue               564\n",
            "Anemia               564\n",
            "Diabetes             564\n",
            "Tuberculosis         564\n",
            "COVID-19             564\n",
            "Asthma               564\n",
            "Influenza            564\n",
            "Hypertension         564\n",
            "Sinusitis            564\n",
            "Migraine             564\n",
            "Common Cold          564\n",
            "Depression           564\n",
            "Gastroenteritis      564\n",
            "Arthritis            564\n",
            "Allergic Rhinitis    564\n",
            "Name: count, dtype: int64\n",
            "\n",
            "Number of classes: 18\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.\n",
            "  warnings.warn(\n",
            "/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: \n",
            "The secret `HF_TOKEN` does not exist in your Colab secrets.\n",
            "To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.\n",
            "You will be able to reuse this secret in all of your notebooks.\n",
            "Please note that authentication is recommended but still optional to access public models or datasets.\n",
            "  warnings.warn(\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "Map:   0%|          | 0/10152 [00:00<?, ? examples/s]"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "589d11050c6d44bdb61bbb100db32051"
            }
          },
          "metadata": {}
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "Train size: 8121, Test size: 2031\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.\n",
            "  warnings.warn(\n",
            "Some weights of BertForSequenceClassification were not initialized from the model checkpoint at monologg/biobert_v1.1_pubmed and are newly initialized: ['classifier.bias', 'classifier.weight']\n",
            "You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.\n",
            "/usr/local/lib/python3.12/dist-packages/notebook/notebookapp.py:191: SyntaxWarning: invalid escape sequence '\\/'\n",
            "  | |_| | '_ \\/ _` / _` |  _/ -_)\n",
            "\u001b[34m\u001b[1mwandb\u001b[0m: (1) Create a W&B account\n",
            "\u001b[34m\u001b[1mwandb\u001b[0m: (2) Use an existing W&B account\n",
            "\u001b[34m\u001b[1mwandb\u001b[0m: (3) Don't visualize my results\n"
          ]
        },
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "\u001b[34m\u001b[1mwandb\u001b[0m: Enter your choice: 3\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "\u001b[34m\u001b[1mwandb\u001b[0m: You chose \"Don't visualize my results\"\n",
            "\u001b[34m\u001b[1mwandb\u001b[0m: Using W&B in offline mode.\n",
            "\u001b[34m\u001b[1mwandb\u001b[0m: W&B API key is configured. Use \u001b[1m`wandb login --relogin`\u001b[0m to force relogin\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.HTML object>"
            ],
            "text/html": []
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.HTML object>"
            ],
            "text/html": [
              "Tracking run with wandb version 0.27.2"
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.HTML object>"
            ],
            "text/html": [
              "W&B syncing is set to <code>`offline`<code> in this directory. Run <code>`wandb online`<code> or set <code>WANDB_MODE=online<code> to enable cloud syncing.<br>Run data is saved locally in <code>/content/wandb/offline-run-20260617_140638-trnx9k2w</code>"
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.HTML object>"
            ],
            "text/html": [
              "\n",
              "    <div>\n",
              "      \n",
              "      <progress value='1016' max='2540' style='width:300px; height:20px; vertical-align: middle;'></progress>\n",
              "      [1016/2540 03:18 < 04:58, 5.11 it/s, Epoch 4/10]\n",
              "    </div>\n",
              "    <table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              " <tr style=\"text-align: left;\">\n",
              "      <th>Epoch</th>\n",
              "      <th>Training Loss</th>\n",
              "      <th>Validation Loss</th>\n",
              "      <th>Accuracy</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <td>1</td>\n",
              "      <td>0.020100</td>\n",
              "      <td>0.011168</td>\n",
              "      <td>1.000000</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <td>2</td>\n",
              "      <td>0.006100</td>\n",
              "      <td>0.003776</td>\n",
              "      <td>1.000000</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <td>3</td>\n",
              "      <td>0.003400</td>\n",
              "      <td>0.002126</td>\n",
              "      <td>1.000000</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <td>4</td>\n",
              "      <td>0.002200</td>\n",
              "      <td>0.001442</td>\n",
              "      <td>1.000000</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table><p>"
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "✅ Model saved successfully\n"
          ]
        }
      ],
      "source": [
        "# -*- coding: utf-8 -*-\n",
        "\"\"\"\n",
        "medical_diagnosis_ai.py\n",
        "Run on Google Colab\n",
        "\"\"\"\n",
        "\n",
        "# Install libraries\n",
        "# !pip install -U transformers datasets torch scikit-learn pandas accelerate sentencepiece\n",
        "\n",
        "import pandas as pd\n",
        "import re\n",
        "import numpy as np\n",
        "import torch\n",
        "import json\n",
        "\n",
        "from datasets import Dataset\n",
        "from transformers import (\n",
        "    BertTokenizer,\n",
        "    AutoModelForSequenceClassification,\n",
        "    Trainer,\n",
        "    TrainingArguments,\n",
        "    EarlyStoppingCallback\n",
        ")\n",
        "\n",
        "from sklearn.utils import resample\n",
        "from sklearn.metrics import accuracy_score\n",
        "from sklearn.model_selection import train_test_split\n",
        "\n",
        "\n",
        "# ──────────────────────────────────────────────\n",
        "# 1. Load dataset\n",
        "# ──────────────────────────────────────────────\n",
        "data = pd.read_csv(\"/content/medical_dataset.csv\")\n",
        "print(\"Original shape:\", data.shape)\n",
        "print(data['condition'].value_counts())\n",
        "\n",
        "\n",
        "# ──────────────────────────────────────────────\n",
        "# 2. Clean symptoms text\n",
        "# ──────────────────────────────────────────────\n",
        "def clean_symptoms(text):\n",
        "    text = re.sub(\n",
        "        r\"The patient experiences?|Patient (has|reports?|experiences?)\",\n",
        "        \"\",\n",
        "        text,\n",
        "        flags=re.IGNORECASE\n",
        "    )\n",
        "    text = re.sub(r\"\\s+\", \" \", text).strip().lower()\n",
        "    return text\n",
        "\n",
        "data['symptoms'] = data['symptoms'].apply(clean_symptoms)\n",
        "\n",
        "\n",
        "# ──────────────────────────────────────────────\n",
        "# 3. Balance dataset\n",
        "# ──────────────────────────────────────────────\n",
        "target_count = int(data['condition'].value_counts().max())\n",
        "\n",
        "balanced_dfs = []\n",
        "\n",
        "for condition in data['condition'].unique():\n",
        "    df_c = data[data['condition'] == condition]\n",
        "\n",
        "    df_r = resample(\n",
        "        df_c,\n",
        "        replace=True,\n",
        "        n_samples=target_count,\n",
        "        random_state=42\n",
        "    )\n",
        "\n",
        "    balanced_dfs.append(df_r)\n",
        "\n",
        "data = pd.concat(balanced_dfs).sample(\n",
        "    frac=1,\n",
        "    random_state=42\n",
        ").reset_index(drop=True)\n",
        "\n",
        "print(\"\\nAfter balancing:\", data.shape)\n",
        "print(data['condition'].value_counts())\n",
        "\n",
        "\n",
        "# ──────────────────────────────────────────────\n",
        "# 4. Encode labels\n",
        "# ──────────────────────────────────────────────\n",
        "unique_conditions = sorted(data['condition'].unique())\n",
        "\n",
        "label_map = {\n",
        "    condition: i\n",
        "    for i, condition in enumerate(unique_conditions)\n",
        "}\n",
        "\n",
        "data['labels'] = data['condition'].map(label_map)\n",
        "\n",
        "num_labels = len(unique_conditions)\n",
        "\n",
        "print(f\"\\nNumber of classes: {num_labels}\")\n",
        "\n",
        "with open(\"labels.json\", \"w\") as f:\n",
        "    json.dump(label_map, f)\n",
        "\n",
        "\n",
        "# ──────────────────────────────────────────────\n",
        "# 5. Tokenizer\n",
        "# ──────────────────────────────────────────────\n",
        "model_name = \"monologg/biobert_v1.1_pubmed\"\n",
        "\n",
        "tokenizer = BertTokenizer.from_pretrained(model_name)\n",
        "\n",
        "def tokenize(example):\n",
        "    tokens = tokenizer(\n",
        "        example[\"symptoms\"],\n",
        "        padding=\"max_length\",\n",
        "        truncation=True,\n",
        "        max_length=64\n",
        "    )\n",
        "\n",
        "    tokens[\"labels\"] = example[\"labels\"]\n",
        "    return tokens\n",
        "\n",
        "\n",
        "# ──────────────────────────────────────────────\n",
        "# 6. Dataset\n",
        "# ──────────────────────────────────────────────\n",
        "dataset = Dataset.from_pandas(\n",
        "    data[['symptoms', 'labels']]\n",
        ")\n",
        "\n",
        "tokenized_dataset = dataset.map(\n",
        "    tokenize,\n",
        "    batched=True\n",
        ")\n",
        "\n",
        "tokenized_dataset.set_format(\n",
        "    type=\"torch\",\n",
        "    columns=[\"input_ids\", \"attention_mask\", \"labels\"]\n",
        ")\n",
        "\n",
        "train_test = tokenized_dataset.train_test_split(\n",
        "    test_size=0.2,\n",
        "    seed=42\n",
        ")\n",
        "\n",
        "train_dataset = train_test[\"train\"]\n",
        "test_dataset = train_test[\"test\"]\n",
        "\n",
        "print(\n",
        "    f\"\\nTrain size: {len(train_dataset)}, \"\n",
        "    f\"Test size: {len(test_dataset)}\"\n",
        ")\n",
        "\n",
        "\n",
        "# ──────────────────────────────────────────────\n",
        "# 7. Model\n",
        "# ──────────────────────────────────────────────\n",
        "model = AutoModelForSequenceClassification.from_pretrained(\n",
        "    model_name,\n",
        "    num_labels=num_labels\n",
        ")\n",
        "\n",
        "\n",
        "# ──────────────────────────────────────────────\n",
        "# 8. Metrics\n",
        "# ──────────────────────────────────────────────\n",
        "def compute_metrics(eval_pred):\n",
        "    logits, labels = eval_pred\n",
        "    preds = np.argmax(logits, axis=1)\n",
        "\n",
        "    return {\n",
        "        \"accuracy\": accuracy_score(labels, preds)\n",
        "    }\n",
        "\n",
        "\n",
        "# ──────────────────────────────────────────────\n",
        "# 9. Training Arguments\n",
        "# ──────────────────────────────────────────────\n",
        "training_args = TrainingArguments(\n",
        "    output_dir=\"./results\",\n",
        "\n",
        "    evaluation_strategy=\"epoch\",\n",
        "    save_strategy=\"epoch\",\n",
        "\n",
        "    load_best_model_at_end=True,\n",
        "    metric_for_best_model=\"accuracy\",\n",
        "\n",
        "    num_train_epochs=10,\n",
        "    learning_rate=3e-5,\n",
        "\n",
        "    per_device_train_batch_size=32,\n",
        "    per_device_eval_batch_size=32,\n",
        "\n",
        "    weight_decay=0.01,\n",
        "\n",
        "    logging_steps=50,\n",
        "\n",
        "    fp16=torch.cuda.is_available()\n",
        ")\n",
        "\n",
        "\n",
        "# ──────────────────────────────────────────────\n",
        "# 10. Trainer\n",
        "# ──────────────────────────────────────────────\n",
        "trainer = Trainer(\n",
        "    model=model,\n",
        "    args=training_args,\n",
        "    train_dataset=train_dataset,\n",
        "    eval_dataset=test_dataset,\n",
        "    compute_metrics=compute_metrics,\n",
        "    callbacks=[\n",
        "        EarlyStoppingCallback(\n",
        "            early_stopping_patience=3\n",
        "        )\n",
        "    ]\n",
        ")\n",
        "\n",
        "trainer.train()\n",
        "\n",
        "\n",
        "# ──────────────────────────────────────────────\n",
        "# 11. Save Model\n",
        "# ──────────────────────────────────────────────\n",
        "model.save_pretrained(\"medical_model\")\n",
        "tokenizer.save_pretrained(\"medical_model\")\n",
        "\n",
        "with open(\"medical_model/labels.json\", \"w\") as f:\n",
        "    json.dump(label_map, f)\n",
        "\n",
        "print(\"✅ Model saved successfully\")"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "!zip -r medical_model.zip medical_model\n",
        "from google.colab import files\n",
        "files.download(\"medical_model.zip\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 145
        },
        "id": "qNEbnLRj78HT",
        "outputId": "b2e42f0a-16f6-4ce8-f279-1aae632b6540"
      },
      "execution_count": 2,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "  adding: medical_model/ (stored 0%)\n",
            "  adding: medical_model/special_tokens_map.json (deflated 42%)\n",
            "  adding: medical_model/labels.json (deflated 36%)\n",
            "  adding: medical_model/tokenizer_config.json (deflated 76%)\n",
            "  adding: medical_model/vocab.txt (deflated 49%)\n",
            "  adding: medical_model/config.json (deflated 61%)\n",
            "  adding: medical_model/model.safetensors (deflated 7%)\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.Javascript object>"
            ],
            "application/javascript": [
              "\n",
              "    async function download(id, filename, size) {\n",
              "      if (!google.colab.kernel.accessAllowed) {\n",
              "        return;\n",
              "      }\n",
              "      const div = document.createElement('div');\n",
              "      const label = document.createElement('label');\n",
              "      label.textContent = `Downloading \"${filename}\": `;\n",
              "      div.appendChild(label);\n",
              "      const progress = document.createElement('progress');\n",
              "      progress.max = size;\n",
              "      div.appendChild(progress);\n",
              "      document.body.appendChild(div);\n",
              "\n",
              "      const buffers = [];\n",
              "      let downloaded = 0;\n",
              "\n",
              "      const channel = await google.colab.kernel.comms.open(id);\n",
              "      // Send a message to notify the kernel that we're ready.\n",
              "      channel.send({})\n",
              "\n",
              "      for await (const message of channel.messages) {\n",
              "        // Send a message to notify the kernel that we're ready.\n",
              "        channel.send({})\n",
              "        if (message.buffers) {\n",
              "          for (const buffer of message.buffers) {\n",
              "            buffers.push(buffer);\n",
              "            downloaded += buffer.byteLength;\n",
              "            progress.value = downloaded;\n",
              "          }\n",
              "        }\n",
              "      }\n",
              "      const blob = new Blob(buffers, {type: 'application/binary'});\n",
              "      const a = document.createElement('a');\n",
              "      a.href = window.URL.createObjectURL(blob);\n",
              "      a.download = filename;\n",
              "      div.appendChild(a);\n",
              "      a.click();\n",
              "      div.remove();\n",
              "    }\n",
              "  "
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.Javascript object>"
            ],
            "application/javascript": [
              "download(\"download_8ffdd0cc-79a8-4960-91c6-f02dd22ed407\", \"medical_model.zip\", 401376032)"
            ]
          },
          "metadata": {}
        }
      ]
    }
  ],
  "metadata": {
    "accelerator": "GPU",
    "colab": {
      "gpuType": "T4",
      "provenance": []
    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    },
    "language_info": {
      "name": "python"
    },
    "widgets": {
      "application/vnd.jupyter.widget-state+json": {
        "589d11050c6d44bdb61bbb100db32051": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "HBoxModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "HBoxModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "HBoxView",
            "box_style": "",
            "children": [
              "IPY_MODEL_ed4c884dd423419aa35ce0402fc503ef",
              "IPY_MODEL_31b1a5f9011b4fbfb22a29480a450873",
              "IPY_MODEL_4aaa9a4fb3534575984e8e5c0689e752"
            ],
            "layout": "IPY_MODEL_f953f66f4fad411cb0b4c63c59699dfd"
          }
        },
        "ed4c884dd423419aa35ce0402fc503ef": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "HTMLModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "HTMLModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "HTMLView",
            "description": "",
            "description_tooltip": null,
            "layout": "IPY_MODEL_7bef11aa7ed74b2295b900735c6c5e7f",
            "placeholder": "​",
            "style": "IPY_MODEL_695cd5959b99474fb8863b9edc8ae647",
            "value": "Map: 100%"
          }
        },
        "31b1a5f9011b4fbfb22a29480a450873": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "FloatProgressModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "FloatProgressModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "ProgressView",
            "bar_style": "success",
            "description": "",
            "description_tooltip": null,
            "layout": "IPY_MODEL_69cd166494b3487a94906728cbb01313",
            "max": 10152,
            "min": 0,
            "orientation": "horizontal",
            "style": "IPY_MODEL_357c012a3cec4abb89541737910dbd52",
            "value": 10152
          }
        },
        "4aaa9a4fb3534575984e8e5c0689e752": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "HTMLModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "HTMLModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "HTMLView",
            "description": "",
            "description_tooltip": null,
            "layout": "IPY_MODEL_cd89bb062d0d4df99cfc693b4fc65caa",
            "placeholder": "​",
            "style": "IPY_MODEL_1d1e04a0918b42fd86455f5f91ad1453",
            "value": " 10152/10152 [00:07&lt;00:00, 1713.27 examples/s]"
          }
        },
        "f953f66f4fad411cb0b4c63c59699dfd": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "7bef11aa7ed74b2295b900735c6c5e7f": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "695cd5959b99474fb8863b9edc8ae647": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DescriptionStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DescriptionStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": ""
          }
        },
        "69cd166494b3487a94906728cbb01313": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "357c012a3cec4abb89541737910dbd52": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "ProgressStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "ProgressStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "bar_color": null,
            "description_width": ""
          }
        },
        "cd89bb062d0d4df99cfc693b4fc65caa": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "1d1e04a0918b42fd86455f5f91ad1453": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DescriptionStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DescriptionStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": ""
          }
        }
      }
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}